#!/usr/bin/env ansible-playbook
#This is adapted from https://github.com/gbraad/dotfiles/blob/master/install.yml
---
- hosts: localhost
  #remote_user: root
  #become: yes
  #become_method: sudo

  tasks:
  - name: Install list of required packages
    package: name={{ item }} state=installed
    become: yes
    become_method: sudo
    with_items:
    - neovim
    - tmux
    - git
    - tmuxinator
    - zsh
    - stow

  - name: Create directory structure
    file: path="{{ item }}" state=directory mode=750
    with_items:
    - "{{ ansible_env.HOME }}/.config"
    - "{{ ansible_env.HOME }}/.local/bin"
  
  - name: Clone dotfiles
    git: repo=https://github.com/heratech/dotfiles2019.git dest={{ ansible_env.HOME }}/.dotfiles

  - name: Install tmux tpm using git
    git: repo=https://github.com/tmux-plugins/tpm dest={{ ansible_env.HOME }}/.tmux/plugins/tpm

  - name: Install Vim Plugged for neovim
    command: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  - name: Stow configurations
    command: chdir={{ ansible_env.HOME }}/.dotfiles stow {{ item }}
    ignore_errors: yes
    with_items:
    - zsh
    - tmux
    - nvim

  - name: Install nvim plugins
    command: nvim +'PlugInstall --sync' +qa

    #  - name: Install tmux plugins 
    #shell: install-tmux-plugins.sh

  - name: Cloning  oh-my-zsh
    git: repo=https://github.com/robbyrussell/oh-my-zsh dest={{ ansible_env.HOME }}/.oh-my-zsh

  - name: Cloning alias-tips into oh my zsh custom folder
    git: repo=https://github.com/djui/alias-tips.git dest={{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/alias-tips
